services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice_support
    restart: always
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    depends_on:
      - postgres_db
  
  nginx:
    image: nginx:latest
    container_name: support_gateway
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - app

  postgres_db:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: